version: '3.9'
services:

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  app:
    build: .
    container_name: app
    image: app
    environment:
      DB_DSN: postgres://user:pass@postgres:5432/postgres?sslmode=disable
    env_file:
      - .env
    ports:
      - 4000:4000
    depends_on:
      - postgres

  integration:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    container_name: integration
    image: integration
    depends_on:
      - app

volumes:
  db-data:
